project_id = "yyusjqaehwvqmbzivwsv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-proposed-deadlines]
    verify_jwt = false
  [functions.send-notification-email]
    verify_jwt = false
  [functions.send-training-reminders]
    verify_jwt = false
